version: '3.8'

services:
  scoreboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: siam-inline-scoreboard
    ports:
      - "3001:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - SUPABASE_URL=
      - SUPABASE_KEY=
    volumes:
      - ./assets:/app/assets
    networks:
      - scoreboard-network

networks:
  scoreboard-network:
    driver: bridge 
