version: '3.9'

name: scoreboard-app

services:
  scoreboard:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV:-production}
      labels:
        org.opencontainers.image.title: "Siam Inline Super League Scoreboard"
        org.opencontainers.image.description: "Real-time hockey scoreboard overlay for OBS"
    container_name: Scorify
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-3000}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    volumes:
      - ./assets:/app/assets:ro
      - scoreboard_logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    security_opt:
      - no-new-privileges:true
    networks:
      - scoreboard-network

volumes:
  scoreboard_logs:
    driver: local

networks:
  scoreboard-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16 